version: '3.1'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      # create app dir using vscode instead of 
      # docker creating it automatically.
      # otherwise EACESS error is caused.
      - ./mongodb/data/:/data/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: users
      MONGODB_DATA_DIR: /mongodb/data/
      # MONDODB_LOG_DIR: /dev/null
    networks:
      - backend
  mongo-express:
    image: mongo-express
    container_name: mongox
    restart: always
    ports:
      - 8081:8081
    environment:
      # fill in popup when opening webui (mongo express)
      ME_CONFIG_BASICAUTH_USERNAME: rootuser
      ME_CONFIG_BASICAUTH_PASSWORD: rootpass
      # admin credentials (mongo express)
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      # db credentials (mongodb service)
      ME_CONFIG_MONGODB_URL: mongodb://rootuser:rootpass@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - backend
  backend:
    image: uff/backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    command: uvicorn main:app --port=8000 --host 0.0.0.0 --reload
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - 8000:8000
    environment:
      MONGODB_URL: mongodb://rootuser:rootpass@mongodb:27017/
    networks:
      - backend
    depends_on:
      - mongodb
      - mongo-express
    restart: on-failure